//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.05 at 01:56:59 PM CET 
//


package com.realityshard.host.schemas.gameapp;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.realityshard.host.schemas.gameapp package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.realityshard.host.schemas.gameapp
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GameApp }
     * 
     */
    public GameApp createGameApp() {
        return new GameApp();
    }

    /**
     * Create an instance of {@link AppInfo }
     * 
     */
    public AppInfo createAppInfo() {
        return new AppInfo();
    }

    /**
     * Create an instance of {@link ShardletConfig }
     * 
     */
    public ShardletConfig createShardletConfig() {
        return new ShardletConfig();
    }

    /**
     * Create an instance of {@link InitParam }
     * 
     */
    public InitParam createInitParam() {
        return new InitParam();
    }

}
